# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resolved_place_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
