from django.urls import path

from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('feed/', views.feed, name='feed'),
    path('jobs/post/', views.post_job, name='post_job'),
    path('jobs/find/', views.find_jobs, name='find_jobs'),
    path('jobs/alerts/', views.create_job_alert, name='create_job_alert'),
    path('jobs/<int:pk>/', views.job_detail, name='job_detail'),
    path('jobs/<int:pk>/like/', views.toggle_like, name='toggle_like'),
    path('jobs/<int:pk>/save/', views.toggle_save, name='toggle_save'),
    path('jobs/<int:pk>/apply/', views.apply_job, name='apply_job'),
    path('jobs/<int:pk>/status/', views.update_job_status, name='update_job_status'),
    path('profiles/edit/', views.edit_profile, name='edit_profile'),
    path('settings/', views.settings_view, name='settings'),
    path('profiles/<str:username>/', views.profile_detail, name='profile_detail'),
    path('profiles/<str:username>/review/', views.review_user, name='review_user'),
    path('profiles/<str:username>/follow/', views.toggle_follow, name='toggle_follow'),
    path('inbox/', views.inbox, name='inbox'),
    path('chat/start/<str:username>/', views.start_conversation, name='start_conversation'),
    path('chat/<int:conversation_id>/', views.chat_room, name='chat_room'),
    path('chat/messages/<int:message_id>/delete-for-me/', views.delete_message_for_me, name='delete_message_for_me'),
    path('chat/messages/<int:message_id>/delete-for-everyone/', views.delete_message_for_everyone, name='delete_message_for_everyone'),
    path('api/chat/<int:conversation_id>/', views.chat_messages_api, name='chat_messages_api'),
    path('api/chat/<int:conversation_id>/typing/', views.chat_typing_api, name='chat_typing_api'),
    path('notifications/', views.notifications, name='notifications'),
    path('api/jobs/', views.jobs_api, name='jobs_api'),
    path('api/geocode/', views.geocode_api, name='geocode_api'),
    path('api/location/', views.update_location, name='update_location'),
]
